name: Build and Deploy LaTeX Resume

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up LaTeX
        uses: dante-ev/latex-action@v2
        with:
          root_file: main.tex
      - name: Check PDF output
        run: |
          if [ ! -f main.pdf ]; then
            echo "PDF not generated!" && exit 1
          fi
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume-pdf
          path: main.pdf

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up LaTeX
        uses: dante-ev/latex-action@v2
        with:
          root_file: main.tex
      - name: Check PDF output
        run: |
          if [ ! -f main.pdf ]; then
            echo "PDF not generated!" && exit 1
          fi
      - name: Commit and push PDF and update README
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mv main.pdf resume.pdf
          sed -i '/<!-- The PDF will be embedded here by the CI\/CD workflow. -->/a \\n[Download the latest resume (PDF)](./resume.pdf)\\n' README.md
          git add resume.pdf README.md
          git commit -m "Update resume PDF and README.md [auto]" || echo "No changes to commit"
          git push 