name: Build and Release LaTeX Resume

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up LaTeX
        uses: dante-ev/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
          args: -lualatex
      - name: Check PDF output
        run: |
          if [ ! -f main.pdf ]; then
            echo "PDF not generated!" && exit 1
          fi
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: main.pdf
          if-no-files-found: error

  release:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: resume-pdf
          path: dist
      - name: Prepare release asset
        run: |
          TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
          mv dist/main.pdf "dist/resume-${TIMESTAMP}.pdf"
          echo "ASSET=dist/resume-${TIMESTAMP}.pdf" >> $GITHUB_ENV
          echo "REL_TAG=build-${{ github.run_id }}" >> $GITHUB_ENV
          echo "REL_NAME=Automated Resume Build ${TIMESTAMP}" >> $GITHUB_ENV
      - name: Create prerelease with PDF
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.REL_TAG }}
          name: ${{ env.REL_NAME }}
          body: |
            Automated build from commit ${{ github.sha }}.

            - Branch: ${{ github.ref_name }}
            - Run ID: ${{ github.run_id }}
          prerelease: true
          artifacts: ${{ env.ASSET }}
          makeLatest: false
          allowUpdates: true 