name: Monthly Resume Release

on:
  schedule:
    # Run on the 1st of every month at 9:00 AM UTC
    - cron: '0 9 1 * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up LaTeX
        uses: dante-ev/latex-action@v2
        with:
          root_file: main.tex
          
      - name: Check PDF output
        run: |
          if [ ! -f main.pdf ]; then
            echo "PDF not generated!" && exit 1
          fi
          
      - name: Prepare release files
        run: |
          # Rename PDF with timestamp
          TIMESTAMP=$(date +"%Y-%m")
          mv main.pdf "resume-${TIMESTAMP}.pdf"
          echo "RELEASE_FILE=resume-${TIMESTAMP}.pdf" >> $GITHUB_ENV
          echo "RELEASE_TAG=monthly-v${TIMESTAMP}" >> $GITHUB_ENV
          echo "RELEASE_TITLE=Monthly Resume Release ${TIMESTAMP}" >> $GITHUB_ENV
          echo "CURRENT_DATE=$(date +"%B %d, %Y")" >> $GITHUB_ENV
          
      - name: Create/Update Monthly Release with PDF
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TITLE }}
          body: |
            📄 **Monthly Resume Release**

            This is an automatically generated monthly release of the resume PDF.

            **Generated on:** ${{ env.CURRENT_DATE }}
            **Build ID:** ${{ github.run_id }}

            ### What's included:
            - 📋 Latest resume in PDF format
            - 🔄 Auto-generated from LaTeX source

            ---
            *This release was automatically created by GitHub Actions*
          artifacts: ${{ env.RELEASE_FILE }}
          makeLatest: true
          allowUpdates: true